/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelos.Tarea;
import servicios.Conexion;
import servicios.Tareas_servicio;

/**
 *
 * @author Master Kaizen - MK
 */
public class vista_guardar_cliente extends javax.swing.JFrame {
    
    private final Tareas_servicio tareas_servicio = new Tareas_servicio();
    private final Tarea tarea;
    /**
     * Creates new form vista_guardar_cliente
     */
    public vista_guardar_cliente() {
        this.tarea = new Tarea();
        initComponents();
    }
    
    public vista_guardar_cliente(Tarea p_tarea){
        this.tarea = p_tarea;
        initComponents();
        elemento_dni.setText(this.tarea.getDos());
        elemento_nombre.setText(this.tarea.getTres());
        elemento_estado.setSelectedItem(this.tarea.getCuatro().toString());
        elemento_tipo.setSelectedItem(this.tarea.getCinco().toString());
        System.out.println(elemento_dni);
        System.out.println(elemento_nombre);
        System.out.println(elemento_estado);
        System.out.println(elemento_tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        elemento_dni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        elemento_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        elemento_tipo = new javax.swing.JComboBox<>();
        elemento_guardar = new javax.swing.JButton();
        elemento_cancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        elemento_estado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DNI/RUC");

        jLabel2.setText("Nombre/R. Social");

        jLabel3.setText("Tipo");

        elemento_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "P" }));

        elemento_guardar.setText("Guardar");
        elemento_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemento_guardarActionPerformed(evt);
            }
        });

        elemento_cancelar.setText("Cancelar");
        elemento_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemento_cancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado");

        elemento_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        elemento_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemento_estadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(elemento_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(elemento_cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(elemento_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addComponent(elemento_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(elemento_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elemento_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(elemento_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(elemento_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(elemento_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(elemento_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elemento_guardar)
                    .addComponent(elemento_cancelar))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elemento_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemento_guardarActionPerformed
        // TODO add your handling code here:
        if(this.validar()){
            this.guardar();
        }else{
            JOptionPane.showMessageDialog(this, "Hay campos incompletos.");
        }
    }//GEN-LAST:event_elemento_guardarActionPerformed

    private void elemento_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemento_cancelarActionPerformed
        // TODO add your handling code here:
        vista_guardar_cliente.this.dispose();
        vista_cliente vista = new vista_cliente();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
    }//GEN-LAST:event_elemento_cancelarActionPerformed

    private void elemento_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemento_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elemento_estadoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // TODO add your handling code here:
        try{
            Conexion.cerrar();
            System.out.println("Conexión cerrada.");
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }                                  

    private boolean validar(){
        boolean validado = true;
        String dni = elemento_dni.getText();
        String descripcion = elemento_nombre.getText();
        //String tipo;
        Integer estado;
        if(!dni.trim().equals("") && !descripcion.trim().equals("")){
            try{
                estado = Integer.parseInt(elemento_estado.getSelectedItem().toString());
                //tipo = elemento_tipo.getSelectedItem().toString();
            }catch(Exception ex){
                validado = false;
            }
        }else{
            validado = false;
        }
        return validado;
    }
    
    private void guardar(){
        String dni = elemento_dni.getText();
        String descripcion = elemento_nombre.getText();
        Integer estado = Integer.parseInt(elemento_estado.getSelectedItem().toString());
        String tipo = elemento_tipo.getSelectedItem().toString();
        
        //this.tarea.setUno();
        this.tarea.setDos(dni);
        this.tarea.setTres(descripcion);
        this.tarea.setCuatro(estado);
        this.tarea.setCinco(tipo);
        try{
            this.tareas_servicio.guardar(Conexion.obtener(), this.tarea);
            vista_guardar_cliente.this.dispose();
            vista_cliente vista = new vista_cliente();
            vista.setVisible(true);
            vista.setLocationRelativeTo(null);
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se ha podido guardar el registro.");
        }catch(ClassNotFoundException ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se ha podido guardar el registro.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_guardar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_guardar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_guardar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_guardar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_guardar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton elemento_cancelar;
    private javax.swing.JTextField elemento_dni;
    private javax.swing.JComboBox<String> elemento_estado;
    private javax.swing.JButton elemento_guardar;
    private javax.swing.JTextField elemento_nombre;
    private javax.swing.JComboBox<String> elemento_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
